export const Z_INDEX = {
  CART_OVERLAY: 120,
  PRODUCT_SELECTION: 100,
  NAV_BAR: 80,
  MOBILE_PRODUCT_SELECTION: 70,
  BANNER: 50,
  COLLECTION_OVERLAY: 20,
  COLLECTION_DROPDOWN: 15,
  CHECKOUT_BAR: 12
};
